### ISSUE TITLE
Only set active once in the owner process

### ISSUE THREAD

**Issue by ray-sh** [whatyouhide/protohackers_in_elixir#1]
Is there a change the acceptor will receive msg from client before it handle the owner to connection? Then this message will never reach to the connection handler.

https://github.com/whatyouhide/protohackers_in_elixir/blob/main/apps/speed_daemon/lib/speed_daemon/acceptor.ex#L16

**Comment by whatyouhide** [comment]
I’m not sure I follow, but setting `active: :once` when listening for connections means that all the accepted sockets will start out with that option set. 🙃

**Comment by ray-sh** [comment]
I mean here https://github.com/whatyouhide/protohackers_in_elixir/blob/main/apps/speed_daemon/lib/speed_daemon/connection_supervisor.ex#L13

Maybe there is a chance msg entered the socket's buffer before :gen_tcp.controlling_process(socket, pid) happend.
Then the message will be send to current process not the pid we wanted.

**Comment by whatyouhide** [comment]
`:gen_tcp.controlling_process/2` transfers messages to the new owner even if they're already in the mailbox.

> If the socket is set in active mode, this function will transfer any messages in the mailbox of the caller to the new controlling process

(from [the docs](https://erlang.org/doc/man/gen_tcp.html#controlling_process-2))
