### ISSUE TITLE
why does the following test fail with your prices server?

### ISSUE THREAD

**Issue by Dowwie** [whatyouhide/protohackers_in_elixir#2]
While testing whether the server would support at least 5 connections, I came across something I didn't clearly understand.  I had an intuition about lifetimes because of my experiences with Rust, and that intuition turned out to be true, but I don't understand what's happening in Elixir.

If we were to add the following test to your prices_server_test.ex, it would fail if we move the socket creation line into the scope of the Task (just before the sends):

This works:
```elixir

    test "at least five simultaneous clients are supported" do
      {:ok, supervisor} = Task.Supervisor.start_link(max_children: 100)

      result =
        0..50
        |> Enum.map(fn _ ->
          {:ok, socket} = :gen_tcp.connect(~c"localhost", 5003, mode: :binary, active: false)

          Task.Supervisor.async(supervisor, fn ->
            :ok = :gen_tcp.send(socket, <<?I, 12345::32-signed-big, 101::32-signed-big>>)
            :ok = :gen_tcp.send(socket, <<?I, 12346::32-signed-big, 102::32-signed-big>>)
            :ok = :gen_tcp.send(socket, <<?I, 12347::32-signed-big, 100::32-signed-big>>)
            :ok = :gen_tcp.send(socket, <<?I, 40960::32-signed-big, 5::32-signed-big>>)
            :ok = :gen_tcp.send(socket, <<?Q, 12288::32-signed-big, 16384::32-signed-big>>)

            assert {:ok, <<101::32-signed-big>>} == :gen_tcp.recv(socket, 0)

            :ok = :gen_tcp.close(socket)
          end)
        end)
        |> Task.await_many()
    end
```

This doesn't work:
```elixir

    test "at least five simultaneous clients are supported" do
      {:ok, supervisor} = Task.Supervisor.start_link(max_children: 100)

      result =
        0..50
        |> Enum.map(fn _ ->
          Task.Supervisor.async(supervisor, fn ->
            {:ok, socket} = :gen_tcp.connect(~c"localhost", 5003, mode: :binary, active: false)
            :ok = :gen_tcp.send(socket, <<?I, 12345::32-signed-big, 101::32-signed-big>>)
            :ok = :gen_tcp.send(socket, <<?I, 12346::32-signed-big, 102::32-signed-big>>)
            :ok = :gen_tcp.send(socket, <<?I, 12347::32-signed-big, 100::32-signed-big>>)
            :ok = :gen_tcp.send(socket, <<?I, 40960::32-signed-big, 5::32-signed-big>>)
            :ok = :gen_tcp.send(socket, <<?Q, 12288::32-signed-big, 16384::32-signed-big>>)

            assert {:ok, <<101::32-signed-big>>} == :gen_tcp.recv(socket, 0)

            :ok = :gen_tcp.close(socket)
          end)
        end)
        |> Task.await_many()
    end
```

**Comment by whatyouhide** [comment]
What do you mean by "doesn't work"? What errors do you see?

**Comment by Dowwie** [comment]
The relevant part of the error seems to indicate ```{:error, :closed}```.  A socket seems to close before the work is finished within the Task, by the time the receive step is reached.  Interestingly, changing the range from `0..50` to `0..4` resolves the issue, passing the test.

This feels like a race condition problem with sockets and load testing locally.  What are your thoughts?

In case this is relevant, I'm running MacOS on an M1.  ulimit is set to 1024.  This is the only server running on my machine.

**Comment by whatyouhide** [comment]
What's the number of tasks that triggers this? 4 works and 50 doesn't, but maybe finding the trigger number can help debug this. Other than that, I currently don't have much bandwidth to help debug this 😞

**Comment by Dowwie** [comment]
This is the kind of stuff that would be a valuable addition to a "Network Programming in Elixir" book!

`0..5` is the threshold.

**Comment by whatyouhide** [comment]
Ok, good catch, this was due to the `:backlog` option in `:gen_tcp.listen/2`, which defaults to 5 connections. I fixed it the commit above 🙃

**Comment by Dowwie** [comment]
Interesting.  `"The backlog value defines the maximum length that the queue of pending connections can grow to. Defaults to 5."`

Why did the first version of the implementation above work whereas the other failed due to the backlog issue?  The first version handled 100 concurrent connections without backlog changed.

**Comment by whatyouhide** [comment]
In the first version that you posted in the initial comment only one socket is being opened. Is that what you mean?

**Comment by Dowwie** [comment]
My guess is that there's a timing difference between the two examples of code where in the dysfunctional example, Tasks stamped towards the backlog, exceeding the default limit.  Does that seem correct?

I'm referring to the creation of a socket that is passed to the Task vs creating the socket within the Task:
```elixir
        |> Enum.map(fn _ ->
          {:ok, socket} = :gen_tcp.connect(~c"localhost", 5003, mode: :binary, active: false)

          Task.Supervisor.async(supervisor, fn ->
             ....
            :ok = :gen_tcp.close(socket)
          end)
        end)
```

**Comment by whatyouhide** [comment]
If you create the socket outside of the task, it might be that the task finishes execution before the loop reaches the max backlog of sockets, regulating itself and ending up working.
